---
# tasks file for nginx_exporter


- name: nginx_exporter container up
  community.docker.docker_container:
    name: nginx_exporter
    state: started
    restart: yes
    image: nginx/nginx-prometheus-exporter
    command: -nginx.scrape-uri=http://localhost/nginx_status
    ports:
      - "{{ansible_eth1.ipv4.address}}:9113:9113"
  tags: nginx_exporter