---
# tasks file for ssh_key_transfer # Transfer prometheus root ssh key to user node 

- name: SSH key generate on prometheus node
  ansible.builtin.shell:  ssh-keygen -q -b 2048 -t rsa -N "" -C "Prometheus" -f /root/.ssh/id_rsa
  args:
    creates: /root/.ssh/id_rsa
  when: hostvars[inventory_hostname].group_names[0] == "prometheus"

- name: Fetch the keyfile from one prometheus to Ansible node 
  fetch: 
    src: "/root/.ssh/id_rsa.pub"
    dest: "ssh_key_transfer/files/prometheus-id_rsa.pub"
    flat: yes
  when: hostvars[inventory_hostname].group_names[0] == "prometheus"

- name: Copy the key add to authorized_keys using Ansible module
  authorized_key:
    user: user
    state: present
    key: "{{ lookup('file','ssh_key_transfer/files/prometheus-id_rsa.pub')}}"
  when: hostvars[inventory_hostname].group_names[0] == "node"