---
# tasks file for mysql_exporter

- name: mysql_exporter present 
  community.docker.docker_container:
    name: mysql_exporter
    state: present
    image: prom/mysqld-exporter
    ports:
      - "{{ansible_eth1.ipv4.address}}:9104:9104"
    env:
        DATA_SOURCE_NAME: "root:somewordpress@({{ansible_eth1.ipv4.address}}:3306)/"
  tags: mysql_exporter