---

- name: Allow connections tcp on 53,22,80,443 ports
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_ports:
      - "22"
      - "80"
      - "443"
      - "53"
    jump: ACCEPT
  tags: iptables


- name: Allow connections on 53 udp port
  ansible.builtin.iptables:
    chain: INPUT
    protocol: udp
    destination_ports:
      - "53"
    jump: ACCEPT
  tags: iptables

- name: Allow connections on lo and eth1 interfaces
  ansible.builtin.iptables:
    chain: INPUT
    in_interface:
      - "lo"
      - "eth1"
    jump: ACCEPT
  tags: iptables

- name: Allow related and established connections
  ansible.builtin.iptables:
    chain: INPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT
  tags: iptables

- name: -P INPUT DROP
  ansible.builtin.iptables:
    chain: INPUT
    policy: DROP
  tags: iptables