---

- name: Allow connections on 22,80,443 ports
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_ports:
      - "22"
      - "80"
      - "443"
    jump: ACCEPT

- name: Allow connections on lo and eth1 interfaces
  ansible.builtin.iptables:
    chain: INPUT
    in_interface:
      - "lo"
      - "eth1"
    jump: ACCEPT

- name: Allow related and established connections
  ansible.builtin.iptables:
    chain: INPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT

- name: -P INPUT DROP
  ansible.builtin.iptables:
    chain: INPUT
    policy: DROP