---

-
 
  hosts: node
  
  roles: 
    - docker_compose
    - wordpress
    - cadvisor
    - mysql_exporter
    - node_exporter
    - certbot_tls
    - nginx
    - nginx_exporter
    - iptables
  




...