---


-
 
  hosts: prometheus

  roles:
    - ssh_key_transfer


-
 
  hosts: node
  
  roles: 
    - ssh_key_transfer

-
 
  hosts: node
  
  roles: 
    - docker_compose
    - wordpress
    - cadvisor
    - mysql_exporter
    - node_exporter
    - certbot_tls
    - nginx
    - nginx_exporter



-
 
  hosts: prometheus
  
  roles: 
    - docker_compose
    - cadvisor
    - node_exporter
    - certbot_tls
    - nginx
    - nginx_exporter
    - push-gateway
    - prometheus
    - alertmanager
    - grafana
    - backup_scirpt_prometheus




...