---
# tasks file for nginx


- name: Update repositories cache and install all dependicies for Nginx 
  apt:
    name: "{{ item }}"
    state: present
    update_cache: True
  with_items:
    - ca-certificates
    - curl
    - gnupg2
    - lsb-release
    - software-properties-common
    - ubuntu-keyring
  tags: nginx


- name: add nginx GPG key
  apt_key:
    url: https://nginx.org/keys/nginx_signing.key
    state: present
  tags: nginx


- name: add nginx main repository to apt
  apt_repository:
    repo: deb http://nginx.org/packages/mainline/ubuntu {{ansible_distribution_release}} nginx
    state: present
  tags: nginx

- name: Creating a file with mysql credentials for exporter
  copy:
      dest: "/etc/apt/preferences.d/99nginx"
      content: |
        Package: *
        Pin: origin nginx.org
        Pin: release o=nginx
        Pin-Priority: 900
  tags: nginx

- name: install Nginx
  apt:
    name: nginx
    state: latest
    update_cache: yes
  tags: nginx