---
# tasks file for docker

- name: Uninstall old docker
  apt:
    name: "{{ item }}"
    state: absent
  with_items:
    - docker
    - docker-engine
    - docker.io
    - containerd
    - runc
  tags: docker


- name: Update repositories cache and install all dependicies for docker and ansible on Ubuntu node.
  apt:
    name: "{{ item }}"
    state: present
    update_cache: True
  with_items:
    - ca-certificates
    - curl
    - gnupg
    - lsb-release
    - software-properties-common
    - python3-pip
    - virtualenv
    - python3-setuptools
  tags: docker

- name: add docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  tags: docker


- name: add docker repository to apt
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable
    state: present
  tags: docker


- name: install docker
  apt:
    name: "{{item}}"
    state: latest
    update_cache: yes
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
  tags: docker


- name: Be sure that docker.service started
  service:
    name: docker
    state: started
    enabled: yes
  tags: docker


- name: Install Docker Module for Python and docker-compose
  pip:
    name: "{{ item }}"
  with_items:
   - docker
   - docker-compose
  tags: docker