---
groups:
- name: instances
  rules:
  - alert: NginxLatencyHigh
    expr: nginx_http_response_time_seconds{quantile="0.99",method="GET",status=~"2[0-9]*"} > 3
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: Nginx latency high (instance {{ $labels.instance }})
      description: "Nginx p99 latency is higher than 3 seconds\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
  

  - alert: NginxHighHttp4xxErrorRate
    expr: sum by (instance)(rate(nginx_http_response_count_total{status=~"^4.."}[2m])) / sum by (instance)(rate(nginx_http_response_count_total[2m])) * 100 > 5
    for: 2m
    labels:
      severity: critical
    annotations:
      summary: Nginx high HTTP 4xx error rate (instance {{ $labels.instance }})
      description: "Too many HTTP requests with status 4xx (> 5%)\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

  - alert: NginxHighHttp5xxErrorRate
    expr: sum by (instance)(rate(nginx_http_response_count_total{status=~"^5.."}[2m])) / sum by (instance)(rate(nginx_http_response_count_total[2m])) * 100 > 5
    for: 2m
    labels:
      severity: critical
    annotations:
      summary: Nginx high HTTP 5xx error rate (instance {{ $labels.instance }})
      description: "Too many HTTP requests with status 5xx (> 5%)\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"